flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/img/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/img/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/img/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
