name: apptesting
description: "Shorebird testing"
publish_to: "none"
version: 0.8.3+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  intl: ^0.19.0
  meta: ^1.12.0
  path: ^1.9.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - shorebird.yaml
